# Generated by Django 3.2.10 on 2021-12-09 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 16, 59, 33, 120280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 9, 16, 59, 33, 120280, tzinfo=utc)),
        ),
    ]
